import type { APIGatewayEvent, APIGatewayProxyResult, Handler } from "aws-lambda";

// This will import the server build generated by `react-router build`
const build = require("../../build/server");

export const handler: Handler = async (
  event: APIGatewayEvent
): Promise<APIGatewayProxyResult> => {
  const { headers, httpMethod, rawUrl, body } = event;

  const requestHeaders = new Headers();
  for (const [key, value] of Object.entries(headers)) {
    if (value) {
      requestHeaders.set(key, value);
    }
  }

  const request = new Request(rawUrl, {
    method: httpMethod,
    headers: requestHeaders,
    body: body ? Buffer.from(body, "base64") : undefined,
  });

  // The 'requestHandler' is exported from the server build
  const response = await build.requestHandler(request);

  const responseHeaders: { [header: string]: boolean | number | string } = {};
  response.headers.forEach((value, key) => {
    responseHeaders[key] = value;
  });

  return {
    statusCode: response.status,
    headers: responseHeaders,
    body: await response.text(),
  };
};